-- ============================================================
-- Santo Edit · Numeración secuencial de pedidos (Fase 1)
-- Migración: 0003_orders_seq
--
-- La UI (caja/cocina) muestra el número de pedido a partir de `rowNumber`.
-- Antes lo daba la fila de la hoja de Google. Ahora usamos una secuencia
-- propia en Postgres: cada pedido recibe un `seq` correlativo y estable.
-- ============================================================

alter table orders
  add column if not exists seq bigint generated by default as identity;

create index if not exists idx_orders_seq on orders (seq);
